2025-08-04 16:44:10,463 - ERROR - Необработанное исключение: AttributeError: 'MainWindow' object has no attribute 'lineEdit_city_1'
2025-08-04 16:44:10,502 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 18142, in add_double_player_to_list
    ct_1 = my_win.lineEdit_city_1.text()
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'lineEdit_city_1'
